
  var map1 =
  [[ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'r', 'p', 'p', 'r', 'p', 'p', 'p', 's', 'r', 'r'],
   [ 'r', 'r', 's', 's', 'r', 'r', 'r', 'p', 'p', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'p', 's', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']]
  var map2 =
   [ [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
     [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
     [ 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'r', 'r'],
     [ 'r', 'r', 'r', 'w', 'w', 'f', 'f', 'w', 'w', 'g', 'r', 'r', 'r'],
     [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'g', 'r', 'r', 'r'],
     [ 'r', 'r', 'g', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'r', 'r'],
     [ 'r', 'r', 'p', 'f', 'f', 'f', 'w', 'w', 'w', 'r', 'r', 'r', 'r'],
     [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
     [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
     [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']
   ]
  var map3 =[
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'g', 'p', 'p', 'r', 'r', 'r'],
   [ 'r', 'r', 'g', 'w', 'g', 'g', 'g', 'g', 'g', 'g', 'r', 'r', 'r'],
   [ 'r', 'r', 'g', 'g', 'g', 'g', 'g', 'g', 'p', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'w', 'w', 'w', 'w', 'w', 'w', 'p', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'w', 'w', 'w', 'w', 'f', 'f', 'f', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']
  ]
  var map4 = [ 
       ['r','r','r','r','r','r','r','r','r','r'],
       ['r','p','p','p','g','p','p','p','p','r'],
       ['r','r','r','r','r','r','r','r','g','r'],
       ['r','p','p','r','r','p','p','p','g','r'],
       ['r','p','r','r','r','r','r','p','p','r'],
       ['r','p','r','r','r','r','r','r','r','r'],
       ['r','p','p','p','p','p','p','p','p','r'],
       ['r','w','f','f','f','w','w','r','p','r'],
       ['r','r','r','r','r','r','r','r','p','r'],
       ['r','p','p','p','p','r','r','p','p','r'],
       ['r','r','r','r','r','r','r','r','r','r'] ]
  var map5 = [
  ["r", "r", "r", "r", "r", "r", "r", "r", "r", "r"], 
  ["r", "p", "p", "p", "g", "p", "p", "p", "p", "r"], 
  ["r", "p", "w", "f", "w", "f", "w", "p", "s", "r"], 
  ["r", "p", "r", "r", "r", "r", "r", "r", "p", "r"], 
  ["r", "g", "p", "p", "p", "p", "r", "r", "r", "r"], 
  ["r", "p", "r", "r", "r", "r", "r", "r", "r", "r"], 
  ["r", "g", "p", "p", "p", "p", "p", "p", "p", "r"], 
  ["r", "p", "p", "r", "r", "r", "r", "s", "s", "r"], 
  ["r", "f", "p", "p", "p", "p", "p", "p", "p", "r"], 
  ["r", "r", "r", "r", "r", "r", "r", "r", "r", "r"]]

  var map6 = [ 
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'r', 'r'],
   [ 'r', 'r', 'w', 'f', 'w', 'f', 'p', 'p', 'r', 'r'],
   [ 'r', 's', 's', 's', 's', 's', 'w', 'p', 'p', 'r'],
   [ 'r', 's', 'p', 'p', 'p', 'p', 'r', 'f', 'r', 'r'],
   [ 'r', 'p', 'p', 's', 'f', 'g', 'g', 'r', 'r', 'r'],
   [ 'r', 's', 'p', 'p', 'r', 'w', 'g', 'p', 'r', 'r'],
   [ 'r', 'p', 'p', 's', 'r', 'r', 'f', 'p', 'r', 'r'],
   [ 'r', 's', 'p', 'p', 'r', 'p', 'g', 'p', 'r', 'r'],
   [ 'r', 'p', 'p', 's', 'r', 'p', 'f', 'w', 'r', 'r'],
   [ 'r', 's', 'p', 'p', 'r', 'p', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 's', 's', 'p', 'r', 'r', 'r', 'r'],
   [ 'r', 's', 'p', 'p', 'p', 'f', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 's', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 's', 'p', 'p', 'p', 's', 's', 's', 's', 'r'],
   [ 'r', 'r', 'r', 'f', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'r', 'r', 'r', 'r', 'p', 'r'],
   [ 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']
 ]

 var map7 = [ 
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'w', 'f', 'w', 'f', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'g', 'g', 'g', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'p', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']
 ]
 var map8 =
 [ 
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'r', 'r', 'r', 'p', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'g', 'p', 'r', 'p', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'f', 'w', 'p', 'r', 'p', 'g', 'p', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'p', 'r', 'g', 'r', 'f', 'w', 'p', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'w', 'f', 'w', 'w', 'p', 'p', 'p', 'r', 'r'],
   [ 'r', 'r', 'p', 'g', 'p', 'g', 'p', 'p', 'r', 'r', 'g', 'r', 'r'],
   [ 'r', 'r', 'p', 'p', 'g', 'w', 'f', 'p', 'p', 'p', 'p', 'r', 'r'],
   [ 'r', 'r', 'p', 'w', 'w', 'r', 'r', 'r', 'r', 'r', 'g', 'r', 'r'],
   [ 'r', 'r', 'p', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'w', 'r', 'r'],
   [ 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'p', 'r', 'p', 'r'],
   [ 'r', 'r', 'p', 'g', 'p', 'g', 'p', 'g', 'p', 'p', 'r', 'p', 'r'],
   [ 'r', 'r', 'g', 'w', 'w', 'w', 'w', 'w', 'w', 'g', 'w', 'p', 'r'],
   [ 'r', 'r', 'g', 'g', 'w', 'r', 'r', 'r', 'w', 'g', 'w', 'p', 'r'],
   [ 'r', 'p', 'r', 'g', 'g', 'w', 'w', 'w', 'g', 'g', 'w', 'p', 'r'],
   [ 'r', 'p', 'p', 'r', 'g', 'g', 'g', 'g', 'g', 'w', 'p', 'g', 'r'],
   [ 'r', 'r', 'p', 'p', 'r', 'r', 'p', 'r', 'w', 'r', 'r', 'p', 'r'],
   [ 'r', 'r', 'g', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'g', 'r'],
   [ 'r', 'r', 'g', 'r', 'r', 'r', 'r', 'p', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'g', 'r', 'r', 'r', 'r', 'p', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'g', 'r', 'r', 'r', 'r', 'p', 'p', 'p', 'p', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'r', 'r', 'r', 'r', 'r', 'p', 'w', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'p', 'p', 'p', 'g', 'p', 'r', 'r'],
   [ 'r', 'r', 'r', 'p', 'p', 'p', 'p', 'r', 'w', 'g', 'w', 'r', 'r'],
   [ 'r', 'r', 'r', 'p', 'f', 'w', 'f', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'p', 'g', 'p', 'p', 'g', 'p', 'g', 'p', 'r', 'r'],
   [ 'r', 'r', 'r', 'w', 'r', 'w', 'f', 'w', 'w', 'w', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']
 ]

 var map9 =
[ 
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r', 'r'],
   [ 'r', 'r', 'f', 'f', 'f', 'r', 'r', 'p', 'g', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'w', 'p', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'g', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'r', 'p', 'w', 'r'],
   [ 'r', 'w', 'w', 'f', 'p', 'p', 'r', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'g', 'r', 'w', 'g', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'f', 'r', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'w', 'p', 'r', 'g', 'f', 'r'],
   [ 'r', 'p', 'p', 'f', 'p', 'p', 'r', 'p', 'p', 'r'],
   [ 'r', 'r', 'p', 'p', 'p', 'p', 'r', 'g', 'g', 'r'],
   [ 'r', 'p', 'p', 'f', 'p', 'p', 'r', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'g', 'r', 'w', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'f', 'r', 'p', 'g', 'r'],
   [ 'r', 'p', 'p', 'p', 'w', 'p', 'r', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'p', 'p', 'r', 'p', 'p', 'r'],
   [ 'r', 'p', 'g', 'g', 'g', 'p', 'r', 'w', 'p', 'r'],
   [ 'r', 'g', 'p', 'p', 'p', 'p', 'r', 'g', 'p', 'r'],
   [ 'r', 'w', 'f', 'g', 'f', 'p', 'r', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'g', 'r', 'p', 'g', 'r'],
   [ 'r', 'p', 'g', 'f', 'f', 'r', 'r', 'w', 'p', 'r'],
   [ 'r', 'f', 'p', 'r', 'r', 'r', 'r', 'p', 'p', 'r'],
   [ 'r', 'p', 'g', 'p', 'p', 'p', 'r', 'p', 'g', 'r'],
   [ 'r', 'r', 'r', 'w', 'f', 'p', 'r', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'g', 'r', 'g', 'p', 'r'],
   [ 'r', 'p', 'r', 'f', 'r', 'r', 'r', 'w', 'p', 'r'],
   [ 'r', 'g', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']
 ]
 var map10 =
 [ 
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 's', 's', 's', 'r', 'r', 'p', 'p', 'p', 'r'],
   [ 'r', 'g', 'g', 'g', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'r', 'r', 'p', 'p', 'p', 'r'],
   [ 'r', 'f', 'f', 'f', 'r', 'r', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'r', 'g', 'r', 'r', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'r', 'p', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'g', 'r', 'p', 'r', 'r', 'p', 'p', 'p', 'r'],
   [ 'r', 'p', 'r', 'r', 'r', 'r', 'r', 'r', 'w', 'r'],
   [ 'r', 'p', 'r', 'g', 'r', 'r', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'r', 'p', 'p', 'p', 'w', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']
 ]
 var map11 =
 [ 
   [ 'r', 'r', 'f', 'f', 'w', 'f', 'w', 'r', 'r', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'f', 'w', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'w', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'f', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'w', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'f', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'w', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'f', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'w', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'f', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'w', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'f', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'w', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'f', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'w', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'f', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'w', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'f', 'w', 'f', 'w', 'f', 'p', 'p', 'r'],
   [ 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'w', 'r'],
   [ 'r', 'p', 'p', 'f', 'w', 'f', 'w', 'f', 'r', 'r'],
   [ 'r', 'r', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r'],
   [ 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r', 'r']
 ]

  var maps = [map1, map2, map3, map4, map5, map6, map7, map8, map9, map10, map11]

  var map_conf = [
                  MapConf(new Point(2,3), new Point(9,3),false, true, false, ['s']),
                  MapConf(new Point(2,2), new Point(2,5),true, false, false),
                  MapConf(new Point(2,1), new Point(9,6),true, true, true),
                  MapConf(new Point(1,1), new Point(1,9),true, true, true),
                  MapConf(new Point(8,8), new Point(8,1),true, true, true, ['s']), 
                  MapConf(new Point(8,17), new Point(1,1),true, true, true, ['s']),
                  MapConf(new Point(1,8), new Point(1,1),true, true, false, ['s']),
                  MapConf(new Point(1,1), new Point(10,27),true, false, true),
                  MapConf(new Point(1,1), new Point(1,5),true, false, true),
                  MapConf(new Point(1,1), new Point(4,12),true, true, true, ['s']),
                  MapConf(new Point(8,37), new Point(1,1),true, true, true, ['s'])
                  ]

  var enemy = [
                [enemyConf(new Point(4, 5), 2)],[],[],
                [],
                [enemyConf(new Point(4, 6), 2)],
                [enemyConf(new Point(4, 15), 2)],
                [enemyConf(new Point(4, 3), 2)],
                [enemyConf(new Point(2, 11), 2), enemyConf(new Point(8, 22), 4), enemyConf(new Point(1, 23), 2)],
                [],[enemyConf(new Point(4, 5), -10)],
                [enemyConf(new Point(5, 37), -10),
                 enemyConf(new Point(6, 35), -10), enemyConf(new Point(6, 35), 10),
                 enemyConf(new Point(5, 33), -10), enemyConf(new Point(5, 33), 10),
                 enemyConf(new Point(6, 31), -10), enemyConf(new Point(6, 31), 10),
                 enemyConf(new Point(5, 29), -10), enemyConf(new Point(5, 29), 10),
                 enemyConf(new Point(6, 27), -10), enemyConf(new Point(6, 27), 10),
                 enemyConf(new Point(5, 25), -10), enemyConf(new Point(5, 25), 10),
                 enemyConf(new Point(6, 23), -10), enemyConf(new Point(6, 23), 10),
                 enemyConf(new Point(5, 21), -10), enemyConf(new Point(5, 21), 10),
                 enemyConf(new Point(6, 19), -10), enemyConf(new Point(6, 19), 10), enemyConf(new Point(6, 19), 3),
                 enemyConf(new Point(5, 17), -10), enemyConf(new Point(5, 17), 10), enemyConf(new Point(5, 17), -6),
                 enemyConf(new Point(6, 15), -10), enemyConf(new Point(6, 15), 10),
                 enemyConf(new Point(5, 13), -10), enemyConf(new Point(5, 13), 10), enemyConf(new Point(5, 13), -7),
                 enemyConf(new Point(6, 11), -10), enemyConf(new Point(6, 11), 10),
                 enemyConf(new Point(5, 9), -10), enemyConf(new Point(5, 9), 10),
                 enemyConf(new Point(6, 7), -10), enemyConf(new Point(6, 7), 10), enemyConf(new Point(6, 7), 5),
                 enemyConf(new Point(5, 5), -10), enemyConf(new Point(5, 5), 10),
                 enemyConf(new Point(6, 3), -10), enemyConf(new Point(6, 3), 10), enemyConf(new Point(6, 3), -5),
                 enemyConf(new Point(5, 1), -10), enemyConf(new Point(5, 1), 10), enemyConf(new Point(5, 1), 7),
                 enemyConf(new Point(5, 1), -7)]
              ]
                  
